### ISSUE TITLE
Files for retraining the model

### ISSUE THREAD

**Issue by dspengler99** [frankkramer-lab/GERNERMED-pp#1]
Hello,

is it possible to provide a documentation for retraining the existing model?

I am asking because I am using Spacy 3.4, which is working so far, but it produces the warning that a retrained model might be needed if performance issues occur.

Thank you for your answer in advance!

**Comment by j-frei** [comment]
Hello @DSpengler99,

Thank you for your interest in our work.
As far as I know, you can safely ignore the warnings. The models should work fine on newer versions of SpaCy as well.

The basic documentation is provided in the paper itself from a (very) high level point of view.
The actual training code of mine requires an actual refactoring in order to release it for third party users in a meaningful way.
If there is a deeper interest in the training code, I can look into it but probably not in the next weeks/few months.

Releasing the dataset used in training cannot be done without legal caveats. Even if you have access to the source code, you also need to request access to the n2c2 2018 dataset (https://portal.dbmi.hms.harvard.edu/projects/n2c2-2018-t2/).

However, if there is an urgent need to retrain the models (due to incompatibilties), I can do so, and I will probably add another gbert-based model in the future.

I hope that my answer has helped you, and please feel free to comment further in any case, or to reopen this issue. 

Kind regards,
Johann
